#Plataformas

In [ ]:
!pip show numpy

Name: numpy
Version: 1.21.6
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: None
License: BSD
Location: /usr/local/lib/python3.7/dist-packages
Requires: 
Required-by: yellowbrick, xgboost, xarray, xarray-einstats, wordcloud, torchvision, torchtext, tifffile, thinc, tensorflow, tensorflow-probability, tensorflow-hub, tensorflow-datasets, tensorboard, tables, statsmodels, spacy, sklearn-pandas, seaborn, scs, scipy, scikit-learn, scikit-image, resampy, qudida, qdldl, PyWavelets, python-louvain, pystan, pysndfile, pymc, pyerfa, pyemd, pycocotools, pyarrow, prophet, plotnine, patsy, pandas, osqp, opt-einsum, opencv-python, opencv-python-headless, opencv-contrib-python, numexpr, numba, nibabel, netCDF4, moviepy, mlxtend, mizani, missingno, matplotlib, matplotlib-venn, lightgbm, librosa, Keras-Preprocessing, kapre, jpeg4py, jaxlib, jax, imgaug, imbalanced-learn, imageio, hyperopt, https

In [ ]:
!pip show django

In [ ]:
!pip install django

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 7.9 MB 4.3 MB/s 


In [ ]:
import numpy as np

In [ ]:
import pandas as pd

#NumPy

In [6]:
import numpy as np

In [11]:
arreglo = np.array([1, 2, 3, 4, 5])
print('dimensiones: ', arreglo.ndim)
print('shape: ', arreglo.shape)
print('tipo: ', arreglo.dtype)

dimensiones:  1
shape:  (5,)
tipo:  int64


In [13]:
arreglo2 = np.array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6])
print('dimensiones: ', arreglo2.ndim)
print('shape: ', arreglo2.shape)
print('tipo: ', arreglo2.dtype)

dimensiones:  1
shape:  (6,)
tipo:  float64


In [16]:
arreglo3 = np.array([1, 2, 3.3, 4, 5, 6])
print('dimensiones: ', arreglo3.ndim)
print('shape: ', arreglo3.shape)
print('tipo: ', arreglo3.dtype)

dimensiones:  1
shape:  (6,)
tipo:  float64


In [17]:
arreglo4 = np.zeros(10)
arreglo4

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
arreglo5 = np.ones(7)
arreglo5

array([1., 1., 1., 1., 1., 1., 1.])

In [20]:
arreglo6 = np.arange(1, 22, 2)
arreglo6

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

In [21]:
arreglo7 = np.linspace(0, 2, 7)
arreglo7

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        ])

In [22]:
arreglo2

array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6])

In [23]:
arreglo2[3]

4.4

In [24]:
arreglo2[-3]

4.4

In [25]:
arreglo2[2:4]

array([3.3, 4.4])

In [26]:
arreglo2[0: :2]

array([1.1, 3.3, 5.5])

In [29]:
arreglo2[(arreglo2>3.5) & (arreglo2<6)]

array([4.4, 5.5])

In [31]:
arreglo

array([1, 2, 3, 4, 5])

In [32]:
arreglo.sum()

15

In [33]:
arreglo.min()

1

In [34]:
arreglo.mean()

3.0

In [35]:
arreglo2

array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6])

In [36]:
arreglo3

array([1. , 2. , 3.3, 4. , 5. , 6. ])

In [37]:
suma = arreglo2 + arreglo3
suma

array([ 2.1,  4.2,  6.6,  8.4, 10.5, 12.6])

In [43]:
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
matriz

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [41]:
print("dimension: ", matriz.ndim)
print("Forma: ", matriz.shape)
print("tipo: ", matriz.dtype)

dimension:  2
Forma:  (4, 3)
tipo:  int64


In [44]:
matriz[2][1]

8

In [46]:
matriz[1][1:]

array([], shape=(0, 3), dtype=int64)

In [47]:
matriz[matriz<10]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
matriz

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [51]:
matriz2 = np.zeros((5, 5))
matriz2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [53]:
matriz3 = np.arange(5, 101, 5).reshape(5, 4)
matriz3

array([[  5,  10,  15,  20],
       [ 25,  30,  35,  40],
       [ 45,  50,  55,  60],
       [ 65,  70,  75,  80],
       [ 85,  90,  95, 100]])

In [54]:
matriz3.sum()

1050

In [55]:
matriz3.sum(axis=1)

array([ 50, 130, 210, 290, 370])

In [56]:
matriz3.sum(axis=1)[1]

130

In [57]:
matriz3.sum(axis=0)

array([225, 250, 275, 300])

In [58]:
matriz3.min(axis=0)

array([ 5, 10, 15, 20])

In [61]:
matriz3[matriz3>15].sum()

1020

#Pandas

In [62]:
import pandas as pd

In [64]:
serie1 = pd.Series([1, 2, 3, 4], index=['1ro', '2do', '3ro', '4to'])
serie1

1ro    1
2do    2
3ro    3
4to    4
dtype: int64

In [65]:
romanos = pd.Series({'uno':'I', 'dos':'II', 'tres':'III', 'cuatro':'IV'})
romanos

uno         I
dos        II
tres      III
cuatro     IV
dtype: object

In [66]:
romanos['dos']

'II'

In [67]:
romanos[1]

'II'

In [68]:
serie1

1ro    1
2do    2
3ro    3
4to    4
dtype: int64

In [69]:
serie1.sum()

10

In [71]:
datos = pd.DataFrame({
    "peso" : pd.Series([56, 76, 80]),
    "altura": pd.Series([1.68, 1.56, 1.77])
})
datos

peso  altura
0    56    1.68
1    76    1.56
2    80    1.77

In [72]:
datos['peso'].mean()

70.66666666666667

In [73]:
datos['altura'].min()

1.56

In [74]:
nombres = pd.Series(['Mario', 'Jorge', 'Sandra'])
datos['nombre'] = nombres
datos

peso  altura  nombre
0    56    1.68   Mario
1    76    1.56   Jorge
2    80    1.77  Sandra

In [75]:
del datos['altura']

In [76]:
datos

peso  nombre
0    56   Mario
1    76   Jorge
2    80  Sandra

In [79]:
datos = datos.drop(['peso'], axis=1)
#datos.drop(['peso'], axis=1, inplace=True)

In [80]:
datos

nombre
0   Mario
1   Jorge
2  Sandra

In [81]:
datos.drop([1], axis=0, inplace=True)

In [82]:
datos

nombre
0   Mario
2  Sandra

In [83]:
personajes = pd.read_csv('/content/characters.csv')

In [84]:
personajes

id            name  height   mass hair_color   skin_color eye_color  \
0    1  Luke Skywalker     172   77.0      blond         fair      blue   
1    2           C-3PO     167   75.0        NaN         gold    yellow   
2    3           R2-D2      96   32.0        NaN  white, blue       red   
3    4     Darth Vader     202  136.0       none        white    yellow   
4    5     Leia Organa     150   49.0      brown        light     brown   
..  ..             ...     ...    ...        ...          ...       ...   
82  83             Rey     168   77.0      brown        light     hazel   
83  84     Poe Dameron     175   81.0      brown        light     brown   
84  85             BB8      45   60.0       none         none     black   
85  86  Captain Phasma     170   79.0        NaN          NaN       NaN   
86  87   Padmé Amidala     165   45.0      brown        light     brown   

   birth_year  gender homeworld species  
0       19BBY    male  Tatooine   Human  
1      112BBY     NaN  Tatooine   Droid  
2       33BBY     NaN     Naboo   Droid  
3     41.9BBY    male  Tatooine   Human  
4       19BBY  female  Alderaan   Human  
..        ...     ...       ...     ...  
82        NaN  female       NaN   Human  
83        NaN    male       NaN   Human  
84        NaN    none       NaN   Droid  
85        NaN  female       NaN     NaN  
86      46BBY  female     Naboo   Human  

[87 rows x 11 columns]

In [85]:
personajes.head(3)

id            name  height  mass hair_color   skin_color eye_color  \
0   1  Luke Skywalker     172  77.0      blond         fair      blue   
1   2           C-3PO     167  75.0        NaN         gold    yellow   
2   3           R2-D2      96  32.0        NaN  white, blue       red   

  birth_year gender homeworld species  
0      19BBY   male  Tatooine   Human  
1     112BBY    NaN  Tatooine   Droid  
2      33BBY    NaN     Naboo   Droid

In [86]:
personajes.tail(7)

id            name  height  mass hair_color skin_color eye_color  \
80  81      Tion Medon     206  80.0       none       grey     black   
81  82            Finn     177  87.0      black       dark      dark   
82  83             Rey     168  77.0      brown      light     hazel   
83  84     Poe Dameron     175  81.0      brown      light     brown   
84  85             BB8      45  60.0       none       none     black   
85  86  Captain Phasma     170  79.0        NaN        NaN       NaN   
86  87   Padmé Amidala     165  45.0      brown      light     brown   

   birth_year  gender homeworld species  
80        NaN    male    Utapau  Pau'an  
81        NaN    male       NaN   Human  
82        NaN  female       NaN   Human  
83        NaN    male       NaN   Human  
84        NaN    none       NaN   Droid  
85        NaN  female       NaN     NaN  
86      46BBY  female     Naboo   Human

In [87]:
personajes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87 entries, 0 to 86
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   id          87 non-null     int64  
 1   name        87 non-null     object 
 2   height      87 non-null     int64  
 3   mass        87 non-null     float64
 4   hair_color  81 non-null     object 
 5   skin_color  85 non-null     object 
 6   eye_color   84 non-null     object 
 7   birth_year  43 non-null     object 
 8   gender      84 non-null     object 
 9   homeworld   77 non-null     object 
 10  species     82 non-null     object 
dtypes: float64(1), int64(2), object(8)
memory usage: 7.6+ KB


In [88]:
personajes['mass'].mean()

94.24597701149425

In [89]:
datos = pd.DataFrame({
    "peso" : pd.Series([56, 76, 80]),
    "altura": pd.Series([1.68, 1.56, 1.77])
})
datos 

peso  altura
0    56    1.68
1    76    1.56
2    80    1.77

In [90]:
datos.to_excel('/content/datos.xlsx')