#Solución de Retos DSAI - M2 Aprender

**Tema 1: Plataformas / Frameworks**

Crea un nuevo Notebook

*   Verifica si en tu entorno de Colab ya están disponibles las plataformas:
     *   numpy
     *   pandas
*   En caso de que alguna no esté disponible, instálala.





In [ ]:
!pip show numpy 

Name: numpy
Version: 1.19.5
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: None
License: BSD
Location: /usr/local/lib/python3.7/dist-packages
Requires: 
Required-by: yellowbrick, xgboost, xarray, wordcloud, torchvision, torchtext, torch, tifffile, thinc, Theano-PyMC, tensorflow, tensorflow-probability, tensorflow-hub, tensorflow-datasets, tensorboard, tables, statsmodels, spacy, sklearn-pandas, seaborn, scs, scipy, scikit-learn, resampy, qdldl, PyWavelets, python-louvain, pystan, pysndfile, pymc3, pyerfa, pyemd, pyarrow, plotnine, patsy, pandas, osqp, opt-einsum, opencv-python, opencv-contrib-python, numexpr, numba, nibabel, netCDF4, moviepy, mlxtend, mizani, missingno, matplotlib, matplotlib-venn, lightgbm, librosa, Keras, Keras-Preprocessing, kapre, jpeg4py, jaxlib, jax, imgaug, imbalanced-learn, imageio, hyperopt, holoviews, h5py, gym, gensim, folium, fix-yahoo-finance, fbpro

In [ ]:
!pip show pandas

Name: pandas
Version: 1.1.5
Summary: Powerful data structures for data analysis, time series, and statistics
Home-page: https://pandas.pydata.org
Author: None
Author-email: None
License: BSD
Location: /usr/local/lib/python3.7/dist-packages
Requires: pytz, python-dateutil, numpy
Required-by: xarray, vega-datasets, statsmodels, sklearn-pandas, seaborn, pymc3, plotnine, pandas-profiling, pandas-gbq, pandas-datareader, mlxtend, mizani, holoviews, gspread-dataframe, google-colab, fix-yahoo-finance, fbprophet, fastai, cufflinks, cmdstanpy, arviz, altair


**Tema 2: Arreglos y matrices con NumPy**

**Subtema 2.1 Arreglos**

Crear dos arreglos de 7 números enteros con la función arange

In [ ]:
import numpy as np
arr1 = np.arange(1, 71, 10)
arr2 = np.arange(17, 3, -2)
print('arr1: ', arr1)
print('arr2: ', arr2)

arr1:  [ 1 11 21 31 41 51 61]
arr2:  [17 15 13 11  9  7  5]


Obtener el promedio de los mínimos de ambos arreglos

In [ ]:
prom = (arr1.min() + arr2.min())/2
print('Promedio de los mínimos de ambos arreglos: ', prom)

Promedio de los mínimos de ambos arreglos:  3.0


Obtener los elementos de las posiciones pares del primer arreglo

In [ ]:
print('Elementos de las posiciones pares del primer arreglo: ', arr1[1::2])

Elementos de las posiciones pares del primer arreglo:  [11 31 51]


Sumar ambos arreglos, ordenar el resultado y obtener los tres primeros elementos del resultado

In [ ]:
sumaArr = arr1 + arr2
print('Suma de los arreglos: ', sumaArr)
sumaArr.sort()
print('Los tres primeros elementos son: ', sumaArr[:3])


Suma de los arreglos:  [18 26 34 42 50 58 66]
Los tres primeros elementos son:  [18 26 34]


**Subtema 2.2 Matrices**

Definir dos matrices de 5x4 con elementos en serie

In [ ]:
import numpy as np
matriz1 = np.arange(5, 101, 5).reshape(5, 4)
matriz2 = np.arange(400, 0, -20).reshape(5, 4)
print('matriz1: \n', matriz1)
print('matriz2: \n', matriz2)

matriz1: 
 [[  5  10  15  20]
 [ 25  30  35  40]
 [ 45  50  55  60]
 [ 65  70  75  80]
 [ 85  90  95 100]]
matriz2: 
 [[400 380 360 340]
 [320 300 280 260]
 [240 220 200 180]
 [160 140 120 100]
 [ 80  60  40  20]]


Obtener el mínimo y máximo de la primera matriz

In [ ]:
print('Mínimo de la primera matriz: ', matriz1.min())
print('Máximo de la primera matriz: ', matriz1.max())

Mínimo de la primera matriz:  5
Máximo de la primera matriz:  100


La suma de todas las columnas de la primera matriz

In [ ]:
print('Suma de todas las columnas de la primera matriz: \n', matriz1.sum(axis=0))

Suma de todas las columnas de la primera matriz: 
 [225 250 275 300]


La suma de todos los elementos de la segunda y tercer fila de la primera matriz

In [ ]:
print('Suma de todos los elementos de la segunda y tercer fila de la primera matriz: ', (matriz1[1]+matriz1[2]).sum())

Suma de todos los elementos de la segunda y tercer fila de la primera matriz:  340


La suma de los elementos de la tercera y quinta fila de la primera matriz

In [ ]:
print('Suma de los elementos de la tercera y quinta fila de la primera matriz: \n', matriz1.sum(axis=1)[2:5:2])

Suma de los elementos de la tercera y quinta fila de la primera matriz: 
 [210 370]


La suma de las dos matrices

In [ ]:
sumaMatrices = matriz1 + matriz2
print('Suma de las matrices: \n', sumaMatrices)

Suma de las matrices: 
 [[405 390 375 360]
 [345 330 315 300]
 [285 270 255 240]
 [225 210 195 180]
 [165 150 135 120]]


**Tema 3: Estructuras de datos en Pandas**

**Subtema 3.1 Series y Dataframes**

Crear un dataframe que contenga 5 registros de deportistas famosos con su nombre y el deporte que practican

In [ ]:
import pandas as pd
deportistas = pd.DataFrame({
   "Nombre": pd.Series(['Micheal Jordan', 'Lionel Messi', 'Tom Brady', 'Serena Williams']),
   "Deporte": pd.Series(['Baloncesto', 'Fútbol', 'Fútbol Americanco', 'Tenis'])
})
deportistas

Nombre            Deporte
0   Micheal Jordan         Baloncesto
1     Lionel Messi             Fútbol
2        Tom Brady  Fútbol Americanco
3  Serena Williams              Tenis

Agrega una columna de edad con sus valores correspondientes

In [ ]:
edad = pd.Series([58, 33, 43, 39])
print('Edad: \n', edad)
deportistas['Edad'] = edad
print('Deportistas: ') 
deportistas

Edad: 
 0    58
1    33
2    43
3    39
dtype: int64
Deportistas: 


Nombre            Deporte  Edad
0   Micheal Jordan         Baloncesto    58
1     Lionel Messi             Fútbol    33
2        Tom Brady  Fútbol Americanco    43
3  Serena Williams              Tenis    39

Agrega otra columna con nombre "estado", donde todos los registros contengan el valor "ACTIVO"

In [ ]:
deportistas['estado'] = 'ACTIVO'
deportistas

Nombre            Deporte  Edad  estado
0   Micheal Jordan         Baloncesto    58  ACTIVO
1     Lionel Messi             Fútbol    33  ACTIVO
2        Tom Brady  Fútbol Americanco    43  ACTIVO
3  Serena Williams              Tenis    39  ACTIVO

**Tema 4: Manipulando datos Tabulares con Pandas**

**Tema 4.1 Leyendo datos tabulares con Pandas**

Leer archivo

In [ ]:
#tweets = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/TLG/vaccination_tweets.csv')
tweets = pd.read_csv('/content/vaccination_tweets.csv')
tweets

id             user_name  ... favorites is_retweet
0     1.340000e+18            Rachel Roh  ...         0      False
1     1.340000e+18           Albert Fong  ...         1      False
2     1.340000e+18              eli🇱🇹🇪🇺👌  ...         0      False
3     1.340000e+18         Charles Adler  ...      2129      False
4     1.340000e+18  Citizen News Channel  ...         0      False
...            ...                   ...  ...       ...        ...
4275  1.350000e+18          Cate Cammack  ...         8      False
4276  1.350000e+18        SUR in English  ...         2      False
4277  1.350000e+18       Melissa coleman  ...         0      False
4278  1.350000e+18          The Insider🦉  ...         0      False
4279  1.350000e+18         Dr Ai Lyn Tan  ...         5      False

[4280 rows x 16 columns]

Mostrar los primeros 7 registros

In [ ]:
tweets.head(7)

id             user_name  ... favorites is_retweet
0  1.340000e+18            Rachel Roh  ...         0      False
1  1.340000e+18           Albert Fong  ...         1      False
2  1.340000e+18              eli🇱🇹🇪🇺👌  ...         0      False
3  1.340000e+18         Charles Adler  ...      2129      False
4  1.340000e+18  Citizen News Channel  ...         0      False
5  1.340000e+18                   Dee  ...         0      False
6  1.340000e+18     Gunther Fehlinger  ...         4      False

[7 rows x 16 columns]

Mostrar los últimos 4 registros

In [ ]:
tweets.tail(4)

id        user_name  ... favorites is_retweet
4276  1.350000e+18   SUR in English  ...         2      False
4277  1.350000e+18  Melissa coleman  ...         0      False
4278  1.350000e+18     The Insider🦉  ...         0      False
4279  1.350000e+18    Dr Ai Lyn Tan  ...         5      False

[4 rows x 16 columns]

Mostrar la estructura del dataframe y comentar la cantidad de columnas y el tipo de información que contiene

In [ ]:
tweets.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4280 entries, 0 to 4279
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   id                4280 non-null   float64
 1   user_name         4280 non-null   object 
 2   user_location     3398 non-null   object 
 3   user_description  4009 non-null   object 
 4   user_created      4280 non-null   object 
 5   user_followers    4280 non-null   int64  
 6   user_friends      4280 non-null   int64  
 7   user_favourites   4280 non-null   int64  
 8   user_verified     4280 non-null   bool   
 9   date              4280 non-null   object 
 10  text              4280 non-null   object 
 11  hashtags          3188 non-null   object 
 12  source            4279 non-null   object 
 13  retweets          4280 non-null   int64  
 14  favorites         4280 non-null   int64  
 15  is_retweet        4280 non-null   bool   
dtypes: bool(2), float64(1), int64(5), object(8

**Tema 4.2 Escribiendo datos tabulares con Pandas**

Leer el archivo

In [ ]:
tweets = pd.read_csv('/content/vaccination_tweets.csv')
tweets

id             user_name  ... favorites is_retweet
0     1.340000e+18            Rachel Roh  ...         0      False
1     1.340000e+18           Albert Fong  ...         1      False
2     1.340000e+18              eli🇱🇹🇪🇺👌  ...         0      False
3     1.340000e+18         Charles Adler  ...      2129      False
4     1.340000e+18  Citizen News Channel  ...         0      False
...            ...                   ...  ...       ...        ...
4275  1.350000e+18          Cate Cammack  ...         8      False
4276  1.350000e+18        SUR in English  ...         2      False
4277  1.350000e+18       Melissa coleman  ...         0      False
4278  1.350000e+18          The Insider🦉  ...         0      False
4279  1.350000e+18         Dr Ai Lyn Tan  ...         5      False

[4280 rows x 16 columns]

Eliminar la mitad de los registros del dataframe y las columnas necesarias para mantaner solo cuatro de ellas.

In [ ]:
tweets = tweets[0::2][['user_name', 'user_description', 'user_followers', 'user_friends']]
tweets

user_name  ... user_friends
0               Rachel Roh  ...         1692
2                 eli🇱🇹🇪🇺👌  ...           88
4     Citizen News Channel  ...          580
6        Gunther Fehlinger  ...         5001
8              Erin Despas  ...         1515
...                    ...  ...          ...
4270      Sonia Kaur Dhami  ...          155
4272  UZH Medical Virology  ...          583
4274        iJohn González  ...          257
4276        SUR in English  ...          629
4278          The Insider🦉  ...          627

[2140 rows x 4 columns]

Almacenar el nuevo dataframe en un archivo separado por comas llamado "someCharacters.csv"

In [ ]:
tweets.to_csv('/content/someCharacters.csv')

almacenar el nuevo dataframe en un archivo de Excel llamado "someCharacters.xlsx"

In [ ]:
tweets.to_excel('/content/someCharacters.xlsx')