### ***Arreglos en Numpy***


*Creando un arreglo desde una lista de enteros*

In [ ]:
import numpy as np
arreglo1 = np.array([1, 2, 3, 4, 5]) 
print ("Datos:", arreglo1)
print ("Dimensiones: ", arreglo1.ndim)
print ("Forma: ", arreglo1.shape)
print ("Tamaño: ", arreglo1.size)
print ("Tipo: ", arreglo1.dtype)
print ("Tamaño de los elementos: ", arreglo1.itemsize)

Datos: [1 2 3 4 5]
Dimensiones:  1
Forma:  (5,)
Tamaño:  5
Tipo:  int64
Tamaño de los elementos:  8


*Creando un arreglo desde una lista de flotantes*

In [ ]:
import numpy as np
arreglo2 = np.array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9])
print ("Datos:", arreglo2)
print ("Dimensiones: ", arreglo2.ndim)
print ("Forma: ", arreglo2.shape)
print ("Tamaño: ", arreglo2.size)
print ("Tipo: ", arreglo2.dtype)
print ("Tamaño de los elementos: ", arreglo2.itemsize)

Datos: [1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9]
Dimensiones:  1
Forma:  (9,)
Tamaño:  9
Tipo:  float64
Tamaño de los elementos:  8


*Creando un arreglo desde una tupla de flotantes*

In [ ]:
import numpy as np
arreglo3 = np.array((1, 2.2, 3, 4.4, 5, 6.6, 7))
print ("Datos:", arreglo3)
print ("Dimensiones: ", arreglo3.ndim)
print ("Forma: ", arreglo3.shape)
print ("Tamaño: ", arreglo3.size)
print ("Tipo: ", arreglo3.dtype)
print ("Tamaño de los elementos: ", arreglo3.itemsize)

Datos: [1.  2.2 3.  4.4 5.  6.6 7. ]
Dimensiones:  1
Forma:  (7,)
Tamaño:  7
Tipo:  float64
Tamaño de los elementos:  8


*Creando un arreglo de 0s con la función zeros*

In [ ]:
import numpy as np
arreglo4 = np.zeros(4)
print("Datos: ", arreglo4)

Datos:  [0. 0. 0. 0.]


*Creando un arreglo de 1a con la función ones*

In [ ]:
import numpy as np
arreglo5 = np.ones(7)
print("Datos: ", arreglo5)

Datos:  [1. 1. 1. 1. 1. 1. 1.]


*Creando un arreglo de valores sin inicializar, los valores representan valores basura*

In [ ]:
import numpy as np
arreglo6 = np.empty(3)
print("Datos: ", arreglo6)

Datos:  [0.75 0.75 0.  ]


*Creando un arreglo con una secuencia de números enteros con la función arange*

In [ ]:
import numpy
arreglo7 = np.arange(1, 10, 2)
print("arreglo7: ", arreglo7)
arreglo8 = np.arange(0, 3, 0.4)
print("arreglo8: ", arreglo8)

arreglo7:  [1 3 5 7 9]
arreglo8:  [0.  0.4 0.8 1.2 1.6 2.  2.4 2.8]


*Creando un arreglo con una secuencia de números flotantes con la función linspace*

In [ ]:
import numpy as np
arreglo10 = np.linspace(0, 2, 7)
print("arreglo10: ", arreglo10)

arreglo10:  [0.         0.33333333 0.66666667 1.         1.33333333 1.66666667
 2.        ]


*Indexación en arreglos para recuperar sus elementos*

In [ ]:
import numpy as np
arreglo11 = np.array([37, 65, 23, 56, 12])
print("Arreglo:", arreglo11)
print("Accesando al primer elemento individualmente:", arreglo11[0])
print("Accesando al segundo elemento individualmente:", arreglo11[1])
print("Accesando al último elemento individualmente:", arreglo11[4])

Arreglo: [37 65 23 56 12]
Accesando al primer elemento individualmente: 37
Accesando al segundo elemento individualmente: 65
Accesando al último elemento individualmente: 12


*Rebanado/Segmentación/Slicing en arreglos*

In [ ]:
import numpy as np
arreglo12 = np.array([37, 65, 23, 56, 12])
print("Arreglo:", arreglo12)
print("Recuperando los 3 primeros elementos: ", arreglo12[0:3])
print("Recuperando los 3 últimos elementos: ", arreglo12[2:])
print("Recuperando los 3 elementos internos: ", arreglo12[1:-1])

Arreglo: [37 65 23 56 12]
Recuperando los 3 primeros elementos:  [37 65 23]
Recuperando los 3 últimos elementos:  [23 56 12]
Recuperando los 3 elementos internos:  [65 23 56]


*Iterando en arreglos*

In [ ]:
import numpy as np
arreglo13 = np.array([37, 65, 23, 56, 12, 58, 78, 12, 34])
print("Arreglo:", arreglo13)
print("Recuperando los elementos en las posiciones impares: ", arreglo13[::2])
print("Recuperando los elementos en las posiciones pares: ", arreglo13[1::2])
print("Recuperando cada 3 elementos: ", arreglo13[::3])
print("Recuperando los elementos de manera inversa: ", arreglo13[::-1])

Arreglo: [37 65 23 56 12 58 78 12 34]
Recuperando los elementos en las posiciones impares:  [37 23 12 78 34]
Recuperando los elementos en las posiciones pares:  [65 56 58 12]
Recuperando cada 3 elementos:  [37 56 78]
Recuperando los elementos de manera inversa:  [34 12 78 58 12 56 23 65 37]


Obtener elementos con condiciones

In [ ]:
import numpy as np
arreglo13 = np.array([37, 65, 23, 56, 12, 58, 78, 12, 34])
print("Arreglo:", arreglo13)
mayores50 = arreglo13[arreglo13 > 50]
print("Elementos mayores a 50:", mayores50) 
paresMenores60 = arreglo13[(arreglo13 < 60) & (arreglo13%2==0)]
print("Elementos pares menores a 60:", paresMenores60) 

Arreglo: [37 65 23 56 12 58 78 12 34]
Elementos mayores a 50: [65 56 58 78]
Elementos pares menores a 60: [56 12 58 12 34]


*Operaciones con Arreglos: suma de sus elementos, mínimo y máximo*

In [ ]:
import numpy as np
arreglo13 = np.array([37, 65, 23, 56, 12, 58, 78, 12, 34])
print("Arreglo:", arreglo13)
print('La suma de todos sus elementos es: ', arreglo13.sum())
print('El valor mínimo del arreglo es: ', arreglo13.min())
print('El valor máximo del arreglo es: ', arreglo13.max())

Arreglo: [37 65 23 56 12 58 78 12 34]
La suma de todos sus elementos es:  375
El valor mínimo del arreglo es:  12
El valor máximo del arreglo es:  78


*Ordenamiento en arreglos*

In [ ]:
import numpy as np
arreglo13 = np.array([37, 65, 23, 56, 12, 58, 78, 12, 34])
print("Arreglo:", arreglo13)
arreglo13.sort()
print("Arreglo ordenado:", arreglo13)
inverso = np.sort(arreglo13)[::-1]
print("Arreglo ordenando inversamente: ", inverso)

Arreglo: [37 65 23 56 12 58 78 12 34]
Arreglo ordenado: [12 12 23 34 37 56 58 65 78]
Arreglo ordenando inversamente:  [78 65 58 56 37 34 23 12 12]


*Suma de arreglos*

In [ ]:
import numpy as np
a = np.array( [10, 20, 30, 40, 50] )
b = np.array( [1, 2, 3, 4, 5] )
suma = a + b
print("Resultado de la suma de arreglos: \n", suma)

Resultado de la suma de arreglos: 
 [11 22 33 44 55]


### ***Matrices en Numpy***


*Creando una matriz desde una lista de listas de enteros*

In [ ]:
import numpy as np
matriz = np.array([[2, 3, 4], [11, 12, 13], [24, 56, 122], [256, 78, 2]])
print("Matriz:\n", matriz)
print ("Dimensiones: ", matriz.ndim)
print ("Forma: ", matriz.shape)
print ("Tamaño: ", matriz.size)
print ("Tipo: ", matriz.dtype)
print ("Tamaño de los elementos: ", matriz.itemsize)

Matriz:
 [[  2   3   4]
 [ 11  12  13]
 [ 24  56 122]
 [256  78   2]]
Dimensiones:  2
Forma:  (4, 3)
Tamaño:  12
Tipo:  int64
Tamaño de los elementos:  8


*Creando una matriz de ceros*

In [ ]:
import numpy as np
matriz1 = np.zeros((3, 5))
print("Matriz: \n", matriz1)

Matriz: 
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


*Creando una matriz de unos*

In [ ]:
import numpy as np
matriz2 = np.ones((4,2), dtype=np.int16)
print("Matriz: \n", matriz2)

Matriz: 
 [[1 1]
 [1 1]
 [1 1]
 [1 1]]


*Creando una matriz de valores sin inicializar*

In [ ]:
import numpy as np
matriz3 = np.empty((3,3))
print("Matriz: \n", matriz3)

Matriz: 
 [[1.83e-322 3.21e-322 1.14e-322]
 [2.77e-322 5.93e-323 2.87e-322]
 [3.85e-322 5.93e-323 1.68e-322]]


*Creando una matriz a partir de un arreglo con una secuencia de números y después redimensionandolo*

In [ ]:
import numpy as np
matriz4 = np.arange(5, 101, 5).reshape(5, 4)
print("Matriz: \n", matriz4)

Matriz: 
 [[  5  10  15  20]
 [ 25  30  35  40]
 [ 45  50  55  60]
 [ 65  70  75  80]
 [ 85  90  95 100]]


*Idexando y segmentando en una matriz*

In [ ]:
import numpy as np
matriz5 = np.arange(5, 101, 5).reshape(5, 4)
print("Matriz: \n", matriz5)
print("Accesando al segundo elemento de la tercera fila: ", matriz5[2][1])
print("Accesando a todos los elementos de la cuarta fila:", matriz5[3][:])

Matriz: 
 [[  5  10  15  20]
 [ 25  30  35  40]
 [ 45  50  55  60]
 [ 65  70  75  80]
 [ 85  90  95 100]]
Accesando al segundo elemento de la tercera fila:  50
Accesando a todos los elementos de la cuarta fila: [65 70 75 80]


Iterando en una matriz

In [ ]:
import numpy as np
matriz5 = np.arange(5, 101, 5).reshape(5, 4)
print("Matriz: \n", matriz5)
print("Obteniendo los elementos de la fila 4 en las columnas 0, 2: ", matriz5[3][::2])
print(matriz5[::1][2])

Matriz: 
 [[  5  10  15  20]
 [ 25  30  35  40]
 [ 45  50  55  60]
 [ 65  70  75  80]
 [ 85  90  95 100]]
Obteniendo los elementos de la fila 4 en las columnas 0, 2:  [65 75]
[45 50 55 60]


Accesando a los elementos de toda la matriz condicionando

In [ ]:
import numpy as np
matriz5 = np.arange(5, 101, 5).reshape(5, 4)
print("Matriz: \n", matriz5)
print("obteniendo todos los valores mayores a 50 de la matriz: ", matriz5[matriz5>50])

Matriz: 
 [[  5  10  15  20]
 [ 25  30  35  40]
 [ 45  50  55  60]
 [ 65  70  75  80]
 [ 85  90  95 100]]
obteniendo todos los valores mayores a 50 de la matriz:  [ 55  60  65  70  75  80  85  90  95 100]


Operaciones unarias en una matriz: Mínimo, máximo y suma de elementos

In [ ]:
import numpy as np
rg = np.random.default_rng() 
matriz = rg.integers(25, size=(5, 3))
print("Matriz: \n", matriz)
print("Mínimo de los elementos de la matriz: ", matriz.min())
print("Máximo de los elementos de la matriz: ", matriz.max())
print("Suma de los elementos de la matriz: ", matriz.sum())

Matriz: 
 [[19 17  1]
 [ 5  3 15]
 [ 4  3 20]
 [17 20  2]
 [ 5  1  6]]
Mínimo de los elementos de la matriz:  1
Máximo de los elementos de la matriz:  20
Suma de los elementos de la matriz:  138


Operaciones en columnas en una matriz

In [ ]:
import numpy as np
rg = np.random.default_rng() 
matriz = rg.integers(25, size=(5, 3))
print("Matriz: \n", matriz)
print("Mínimo de los elementos de cada columna de la matriz: ", matriz.min(axis=0))
print("Máximo de los elementos de cada columna de la matriz: ", matriz.max(axis=0))
print("Suma de los elementos de cada columna de la matriz: ", matriz.sum(axis=0))

Matriz: 
 [[14  1 18]
 [22 15  0]
 [13 17 20]
 [ 0 20 16]
 [13 15  9]]
Mínimo de los elementos de cada columna de la matriz:  [0 1 0]
Máximo de los elementos de cada columna de la matriz:  [22 20 20]
Suma de los elementos de cada columna de la matriz:  [62 68 63]


Operaciones en filas en una matriz

In [ ]:
import numpy as np
rg = np.random.default_rng() 
matriz = rg.integers(25, size=(5, 3))
print("Matriz: \n", matriz)
print("Mínimo de los elementos de cada fila de la matriz: ", matriz.min(axis=1))
print("Máximo de los elementos de cada fila de la matriz: ", matriz.max(axis=1))
print("Suma de los elementos de cada fila de la matriz: ", matriz.sum(axis=1))
matriz[1:3].sum(axis=1)

Matriz: 
 [[15 16 21]
 [ 7 10 22]
 [21  3 19]
 [ 0 24 17]
 [16 16 18]]
Mínimo de los elementos de cada fila de la matriz:  [15  7  3  0 16]
Máximo de los elementos de cada fila de la matriz:  [21 22 21 24 18]
Suma de los elementos de cada fila de la matriz:  [52 39 43 41 50]


array([39, 43])

*Suma de Matrices*

In [ ]:
import numpy as np
rg = np.random.default_rng() 
MatA = rg.integers(20, size=(3, 3))
MatB = rg.integers(5, size=(3, 3))
sumaMat = MatA + MatB
print("MatA: \n", MatA)
print("MatB: \n", MatB)
print("Suma de MatA + MatB: \n", sumaMat)

MatA: 
 [[18 13 19]
 [ 5  8 17]
 [ 3 12 15]]
MatB: 
 [[3 0 2]
 [2 2 3]
 [3 4 1]]
Suma de MatA + MatB: 
 [[21 13 21]
 [ 7 10 20]
 [ 6 16 16]]
