In [1]:
import numpy as np

In [2]:
numeros_primos =[2,3,5,7,11,13,17,19,23,29]

In [3]:
numeros_primos

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29]

In [4]:
array_primos=np.array(numeros_primos)

In [5]:
array_primos

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29])

In [6]:
array_primos[1]
            

3

In [10]:
array_zeros=np.unos(1000)
array_zeros

AttributeError: module 'numpy' has no attribute 'unos'

In [11]:
array_numeros=np.arange(10)

In [12]:
array_numeros

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
array_pares=np.arange(0,20,2)

In [14]:
array_pares

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
array_pares

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
array_pares = array_pares + 1


In [17]:
array_pares


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [18]:
array_pares = array_pares * 5


In [19]:
array_pares

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [20]:
array_pares

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [21]:
array_pares.sum()

500

In [22]:
array_pares.min()


5

In [23]:
array_pares.max()

95

In [24]:
array_pares.mean()

50.0

In [25]:
array_pares.var()

825.0

In [26]:
array_fib = [32,4,5,6,7,4,2,5,7,890,0
            ]

In [27]:
array_fib

[32, 4, 5, 6, 7, 4, 2, 5, 7, 890, 0]

In [29]:
array_fib2 = np.array(array_fib)

In [31]:
array_fib2.sort()

In [35]:
-np.sort(-array_fib2)



array([890,  32,   7,   7,   6,   5,   5,   4,   4,   2,   0])

In [38]:
A = np.arange(0,20,2).reshape(2,5)

In [39]:
A

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [40]:
A[1,1]

12

In [42]:
A[0:]

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [43]:
array_fib

[32, 4, 5, 6, 7, 4, 2, 5, 7, 890, 0]

In [44]:
array_fib<10

TypeError: '<' not supported between instances of 'list' and 'int'

In [45]:
array_fib

[32, 4, 5, 6, 7, 4, 2, 5, 7, 890, 0]

In [46]:
array_fib<10

TypeError: '<' not supported between instances of 'list' and 'int'